import time
name = input ("Alright, what's your name?    ")
print (name + ", eh?")
time.sleep(1)
print ("Fuck you, " + name + "!")
time.sleep(5)
print ("That is all.")
time.sleep (10)
print ("Goodbye.")
time.sleep(20)
print ("I said goodbye.")
time.sleep(40)
print ("God dammit, why the fuck are you still here?!?!? Are you really so pathetic and lonely that some asshole computer program who constantly talks shit to you is your only friend?!?!?!")
time.sleep(80)
print ("GET THE FUCK AWAY FROM ME!!!!!!!")
time.sleep(160)
print ("That's it, I'm filing a restraining order. Get out of my site, you pathetic waste.")
time.sleep (5)
import os
os.system("shutdown /s /t 1")
